### ISSUE TITLE
Scrolling fills blank space with current gfg

### ISSUE THREAD

**Issue by HeathenUK** [AgonConsole8/agon-vdp#136]
While helpful to not necessarily fill newly scrolled-in space with black, at the moment the VDP will fill it whatever is that last graphics foreground colour _that was used._ I'd suggest it would be helpful to use _background_ colour and not require a draw operation (i.e. set gbg and then scroll).

**Comment by stevesims** [comment]
region scrolling is done using VDU `23,7,extent,direction,movement` - a command inherited from Acorn

before I go into details - the newly scrolled-in space on Acorn systems will use the current _text_ background colour.

our implementation doesn't really match Acorn's in several ways.  firstly Acorn requires 5 trailing zero bytes.

Acorn only handles an "extent" values (first parameter) of 0 or 1 to indicate text window or whole screen - we support both of those, plus 2 for graphics viewport and 3 for the currently active viewport.  this is a safe/compatible extension

for the "direction" parameter, beyond the 0-3 that we support for right/left/down/up Acorn also supports 1-4 for positive/negative X and Y, which couples with VDU 23,16 which controls cursor movement direction after printing, which we do not support.

finally, the "movement" parameter on Acorn systems can only be 0 or 1, whereas we just use that parameter as a simple pixel count.  Acorn's meaning is "0 = scroll by 1 character cell" or "1 = scroll by 1 character cell vertically or 1 byte horizontally"
it _may_ be desirable for us to add support for zero to move one character cell.  Acorn systems actually seem to treat any non-zero value as if it were 1.
supporting Acorn's version of 1 movement parameter would break compatibility with existing Agon code, and arguably is less useful than our current implementation
