### ISSUE TITLE
Add command to enable/disable control-key support

### ISSUE THREAD

**Issue by stevesims** [AgonConsole8/agon-vdp#145]
The VDP supports various ctrl-key combinations.  This behaviour essentially very similar to Acorn systems.

Initially this was just ctrl-N and ctrl-O to enable/disable "paged" mode.  More recently via #140 support for several more combinations has been added.

Handling these combinations on the VDP however means that programs running on MOS have no opportunity to step in and prevent this behaviour.

We should add a command to allow for these control key combinations to be disabled (and re-enabled)

**Comment by lennart-benschop** [comment]
My nano editor makes heavy use of control keys for its functions. It constantly disables paged mode, to neutralize the effect of pressing Control-N. Now we get a lot more side effects of pressing control key combinations. Not too dramatic in the case of nano, but we were just lucky this time. So we certainly want to be able to disable the feature.
