### ISSUE TITLE
Colour mapping seems to be inconsistent

### ISSUE THREAD

**Issue by sijnstra** [AgonConsole8/agon-vdp#248]
Using the init colour mappings to redefine the colours works fine for text/backgrounds but seems to be ignored for characters that are mapped to bitmaps.
![image](https://github.com/user-attachments/assets/c5d07ea4-bfbc-446b-96c8-7d08e475113f)
maps to:
![image](https://github.com/user-attachments/assets/7a54cf30-a0a6-4965-a31f-0e8eef6132ac)
in text but doesn't work right for graphics.
![image](https://github.com/user-attachments/assets/876feffa-795e-4593-919a-2baeff31f813)
produces:
![image](https://github.com/user-attachments/assets/f96465ac-d118-4365-be5e-302b39db83a5)

**Comment by stevesims** [comment]
this issue was caused by the VDP failing to update the RGB222 to palette lookup table when changing palette entries
